### ISSUE TITLE
add debug/development instructions to the readme

### ISSUE THREAD

**Issue by garfieldnate** [sircharleswatson/elm-architecture-hop#12]
I was able to figure out (with enough Googling) how to build and run the application, but I would like to know how to develop on it without doing a full webpack build every time.

**Comment by sircharleswatson** [comment]
I'm not sure what you mean about doing a full build every time. If you use `npm run start` to start up the app, it watches for files changes and updates accordingly.

**Comment by garfieldnate** [comment]
That's great! It even recompiles the elm files and everything? I'm not familiar enough with node/npm to get that off the bat. Just a quick note on building, running and maybe releasing would be very helpful.
